# Generated by Django 5.1.4 on 2025-01-11 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, unique=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('end_of_life_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('repository_url', models.URLField(blank=True, max_length=500, null=True)),
                ('documentation_url', models.URLField(blank=True, max_length=500, null=True)),
                ('popularity_metric', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PythonVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, unique=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('end_of_life_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='example: 3.2.5', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('django_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrix.djangoversion')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrix.package')),
                ('python_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrix.pythonversion')),
            ],
        ),
    ]
