# Generated by Django 5.1.4 on 2025-01-11 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compatibility',
            options={'verbose_name': 'Compatibility', 'verbose_name_plural': 'Compatibilities'},
        ),
        migrations.AlterField(
            model_name='compatibility',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matrix.package'),
        ),
    ]
