# Generated by Django 5.1.4 on 2025-01-12 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0003_alter_compatibility_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djangoversion',
            options={'ordering': ('-release_date',)},
        ),
        migrations.AlterModelOptions(
            name='pythonversion',
            options={'ordering': ('-release_date',)},
        ),
        migrations.AddField(
            model_name='package',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='compatibility',
            name='django_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='matrix.djangoversion'),
        ),
        migrations.AlterField(
            model_name='compatibility',
            name='python_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='matrix.pythonversion'),
        ),
    ]
