# Generated by Django 5.1.4 on 2025-01-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0004_add_slug_to_packages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('-popularity_metric',)},
        ),
        migrations.AlterField(
            model_name='package',
            name='popularity_metric',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
