# Generated by Django 5.1.4 on 2025-01-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0005_alter_package_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('-metric_stars',)},
        ),
        migrations.RenameField(
            model_name='package',
            old_name='popularity_metric',
            new_name='metric_stars',
        ),
        migrations.AddField(
            model_name='package',
            name='metric_forks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='metric_open_issues',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
