# Generated by Django 5.1.4 on 2025-01-12 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0006_packageversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageversion',
            name='django_compatibility',
            field=models.ManyToManyField(to='matrix.djangoversion'),
        ),
        migrations.AddField(
            model_name='packageversion',
            name='python_compatibility',
            field=models.ManyToManyField(to='matrix.pythonversion'),
        ),
        migrations.AlterField(
            model_name='compatibility',
            name='python_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='matrix.pythonversion'),
        ),
    ]
