# Generated by Django 5.1.4 on 2025-01-14 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0006_alter_package_options_and_more'),
        ('matrix', '0007_packageversion_django_compatibility_and_more'),
    ]

    operations = [
    ]
