# Generated by Django 5.1.4 on 2025-01-14 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0008_merge_20250114_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageversion',
            name='django_compatibility',
            field=models.ManyToManyField(blank=True, to='matrix.djangoversion'),
        ),
        migrations.AlterField(
            model_name='packageversion',
            name='python_compatibility',
            field=models.ManyToManyField(blank=True, to='matrix.pythonversion'),
        ),
        migrations.CreateModel(
            name='PackageRepoStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField(default=0)),
                ('forks', models.PositiveIntegerField(default=0)),
                ('open_issues', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_stats', to='matrix.package')),
            ],
        ),
    ]
