# Generated by Django 5.1.4 on 2025-01-14 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0009_alter_packageversion_django_compatibility_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagerepostats',
            options={'verbose_name_plural': 'Package repo stats'},
        ),
        migrations.RenameField(
            model_name='packagerepostats',
            old_name='forks',
            new_name='metric_forks',
        ),
        migrations.RenameField(
            model_name='packagerepostats',
            old_name='open_issues',
            new_name='metric_open_issues',
        ),
        migrations.RenameField(
            model_name='packagerepostats',
            old_name='stars',
            new_name='metric_stars',
        ),
    ]
