# Generated by Django 5.1.4 on 2025-01-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0010_alter_packagerepostats_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('repository_url', models.URLField()),
                ('documentation_url', models.URLField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
