# Generated by Django 5.1.4 on 2025-01-16 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0011_packagerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagerepostats',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Package repo stats'},
        ),
    ]
