# Generated by Django 5.1.4 on 2025-01-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0012_alter_packagerepostats_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageversion',
            name='version',
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name='packageversion',
            constraint=models.UniqueConstraint(fields=('package', 'version'), name='unique_package_version'),
        ),
    ]
