# Generated by Django 5.1.4 on 2025-01-17 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0013_alter_packageversion_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageversion',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='matrix.package'),
        ),
    ]
