# Generated by Django 5.1.4 on 2025-01-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0014_alter_packageversion_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagerepostats',
            name='metric_last_commit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
