# Generated by Django 5.1.4 on 2025-01-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0015_packagerepostats_metric_last_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='metric_last_commit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
