# Generated by Django 5.1.4 on 2025-01-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0016_package_metric_last_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagerequest',
            name='django_compatible_versions',
            field=models.ManyToManyField(blank=True, to='matrix.djangoversion'),
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='latest_version',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
