# Generated by Django 5.1.4 on 2025-01-23 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0017_packagerequest_django_compatible_versions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagerequest',
            name='django_compatible_versions',
            field=models.ManyToManyField(blank=True, help_text='Select all the compatible versions of the package', to='matrix.djangoversion'),
        ),
        migrations.CreateModel(
            name='PackageTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='matrix.package')),
            ],
        ),
    ]
