# Generated by Django 5.1.4 on 2025-01-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0020_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('SEEN', 'Seen'), ('REPLIED', 'Replied'), ('IGNORING', 'Ignoring')], default='NEW', max_length=10),
        ),
    ]
