# Generated by Django 5.1.4 on 2025-02-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0022_category_package_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='package',
            name='releases_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
