# Generated by Django 5.1.4 on 2025-02-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0023_alter_category_options_package_releases_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='installable',
            field=models.BooleanField(default=True),
        ),
    ]
