# Generated by Django 5.1.4 on 2025-02-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0024_package_installable'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
