# Generated by Django 5.1.4 on 2025-02-05 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0023_alter_category_options_package_releases_url'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='matrix.package'),
            preserve_default=False,
        ),
    ]
